/*
**
** Copyright (c) 2024, Oracle and/or its affiliates.
** All rights reserved
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
*/
/**
 * Keep in mind that this fille was generated by the svgr tool,
 * so most if not all of the lint errors are expected.
 */
/* eslint-disable tailwindcss/no-custom-classname */
/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable jsdoc/require-jsdoc */

import * as React from 'react';
import type { SVGProps } from 'react';

function SvgOrdsRed(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width={110}
      height={130}
      fill="none"
      viewBox="0 0 110 130"
      {...props}
    >
      <path
        fill="#C74634"
        d="m55 130 42.256-18.958L110 12.865 55 0 0 12.865l12.744 98.177z"
      />
      <path
        fill="#fff"
        d="M55 75.522c-9.249 0-18.934-2.35-22.938-6.77v8.273c0 5.268 10.268 9.533 22.939 9.533s22.939-4.265 22.939-9.533v-8.288c-3.971 4.429-13.663 6.785-22.94 6.785"
      />
      <path
        fill="#fff"
        d="M55.034 73.45c12.669 0 22.939-4.165 22.939-9.303s-10.27-9.303-22.94-9.303c-12.668 0-22.938 4.165-22.938 9.303s10.27 9.303 22.939 9.303M57.013 48.75l1.415-21.044 7.807 1.314L55 12.188 43.766 29.02l7.807-1.314 1.415 21.044zM19.632 28.993c6.09.846 11.872 2.56 16.58 6.77a54 54 0 0 1 4.025 4.435l.355.393 5.192-3.318-3.354 12.608-11.402-6.142v-.189l5.165-1.11c-3.448-7.685-9.793-11.172-17.614-12.587zM90.368 28.993c-6.09.846-11.872 2.56-16.58 6.77a54 54 0 0 0-4.025 4.435l-.356.393-5.191-3.318 3.354 12.608 11.402-6.142v-.189l-5.165-1.11c3.448-7.685 9.793-11.172 17.614-12.587zM55 88.617c-11.14 0-20.477-3.128-22.938-7.326v8.802c0 5.267 10.268 9.533 22.939 9.533S77.94 95.36 77.94 90.093V81.29c-2.435 4.198-11.765 7.326-22.94 7.326"
      />
      <path
        fill="#fff"
        d="M55 101.705c-11.14 0-20.477-3.128-22.938-7.326v8.802c0 5.267 10.268 9.533 22.939 9.533s22.939-4.266 22.939-9.533v-8.802c-2.435 4.204-11.765 7.326-22.94 7.326"
      />
    </svg>
  );
}
export default SvgOrdsRed;
