name: Bug Report
description: File a bug report for issues.
title: "[Bug] <title>"
labels: ["bug"]
projects: ["oracle/16"]
assignees:
  - mig8447
  - dbtools-antcampo
  - LeonSilva15
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: markdown
    attributes:
      value: "## If you plan to send a PR, please add your username to the assignees list."
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error 
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what is the expected behavior.
    validations:
      required: true
  - type: textarea
    id: ss
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: |
        examples:
          - **Device**: iPhone6, Desktop
          - **OS (with version)**: iOS, iOS8.1
          - **Browser**: Chrome, Safari, Stock Browser
          - **Version**: 7.6.3
          - **Shell**: bash, zsh
      value: |
          - Device:
          - OS (with version):
          - Browser:
          - Version:
          - Shell:
      render: markdown
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Anything else?
      description: Links? References? Anything that will give us more context about the issue you are encountering!
    validations:
      required: false
