/*
**
** Copyright (c) 2024, Oracle and/or its affiliates.
** All rights reserved
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
*/
/**
 * Keep in mind that this fille was generated by the svgr tool,
 * so most if not all of the lint errors are expected.
 */
/* eslint-disable react/function-component-definition */
/* eslint-disable tailwindcss/no-custom-classname */
/* eslint-disable react/jsx-props-no-spreading */

import * as React from 'react';
import type { SVGProps } from 'react';

const SvgOrds = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    id="Icon_Art"
    data-name="Icon Art"
    viewBox="0 0 28.8 28.8"
    {...props}
  >
    <defs>
      <style>
        {
          '.cls-1{fill:none;stroke:#312d2a;stroke-miterlimit:10;stroke-width:.8px}'
        }
      </style>
    </defs>
    <path
      d="m20.6 21.72-6.2 2.2-6.2-2.2L6 8.32l8.4-2.8 8.4 2.8z"
      className="cls-1"
    />
    <ellipse cx={14.4} cy={14.5} className="cls-1" rx={3.2} ry={0.78} />
    <path
      d="M17.6 16.38c0 .43-1.43.77-3.2.77s-3.2-.34-3.2-.77M17.6 18.26c0 .43-1.43.78-3.2.78s-3.2-.35-3.2-.78"
      className="cls-1"
    />
    <path
      d="M11.2 14.5v5.65c0 .42 1.43.77 3.2.77s3.2-.35 3.2-.77V14.5M14.4 8.12v3.8M12.8 9.72l1.6-1.6 1.6 1.6M10.8 12.32l-2.4-2.4M10.8 10.12v2.2H8.6M18 12.32l2.4-2.4M18 10.12v2.2h2.2"
      className="cls-1"
    />
  </svg>
);
export default SvgOrds;
