/*
**
** Copyright (c) 2024, Oracle and/or its affiliates.
** All rights reserved
** Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
*/

// Disabling eslint rules since this file was generated by remix
/* eslint-disable require-jsdoc */
/* eslint-disable valid-jsdoc */
/* eslint-disable jsdoc/require-param-description */
/* eslint-disable jsdoc/require-returns */
/* eslint-disable jsdoc/require-jsdoc */
/* eslint-disable no-console */
import type {
  AppLoadContext, EntryContext,
} from '@remix-run/node';
import { RemixServer } from '@remix-run/react';
import { renderToString } from 'react-dom/server';
import { MuiProvider } from './mui/MuiProvider';
import createEmotionCache from './mui/createEmotionCache';
import { Head } from './root';

const HEAD_START = '<!--start head-->';
const HEAD_END = '<!--end head-->';

function renderDocument(
  head: string,
  body: string,
): string {
  return `<!DOCTYPE html><html lang="en"><head>${HEAD_START}${head}${HEAD_END}</head><body><div id="root">${body}</div></body></html>`;
}

/**
 * By default, Remix will handle generating the HTTP Response for you.
 * You are free to delete this file if you'd like to, but if you ever want
 * it revealed again, you can run `npx remix reveal` ✨
 * For more information, see https://remix.run/file-conventions/entry.server
 * @param request
 * @param responseStatusCode
 * @param responseHeaders
 * @param remixContext
 * @param loadContext
 */
export default function handleRequest(
  request: Request,
  responseStatusCode: number,
  responseHeaders: Headers,
  remixContext: EntryContext,
  // This is ignored so we can keep it in the template for visibility.  Feel
  // free to delete this parameter in your app if you're not using it!
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  loadContext: AppLoadContext,
) {
  const rootRouteModule = remixContext.routeModules.root;
  const headContext: EntryContext = {
    ...remixContext,
    routeModules: {
      ...remixContext.routeModules,
      root: {
        ...rootRouteModule,
        default: Head,
        ErrorBoundary: Head,
      },
    },
  };

  const head = renderToString(
    <RemixServer context={headContext} url={request.url} />,
  );

  const body = renderToString(
    <MuiProvider emotionCache={createEmotionCache()}>
      <RemixServer context={remixContext} url={request.url} />
    </MuiProvider>,
  );

  responseHeaders.set('Content-Type', 'text/html');

  return new Response(renderDocument(head, body), {
    headers: responseHeaders,
    status: responseStatusCode,
  });
}
